# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: VSBuild@1
  inputs:
    solution: '**/*.sqlproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    FileCopyOptions: 
    


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name rgwebapp1 --location westus

      az sql server create --name umsdbserver1234 --resource-group rgwebapp1 --admin-user "umsuser" --admin-password "Pass1@34"

      az sql db create --resource-group rgwebapp1 --server umsdbserver1234  --name umsdb --service-objective S3 --collation SQL_Latin1_General_CP1_CI_AS
      
      az appservice plan create --name myappPlan --sku F1 --resource-group rgwebapp1
      
      az webapp create --resource-group rgwebapp1 --name selvanapp123 --plan myappPlan --runtime  "aspnet|v4.7" 
      
      az sql server firewall-rule create -g mygroup -s umsdbserver1234 -n myrule --start-ip-address 0.0.0.0 --end-ip-address 255.255.255.255
 
      
- task: DownloadBuildArtifacts@0
  inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.DefaultWorkingDirectory)'
  enabled: false
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure'
    appType: 'webApp'
    WebAppName: 'selvanapp123'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  enabled: false
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure'
    AuthenticationType: 'server'
    ServerName: 'umsdbserver1234.database.windows.net'
    DatabaseName: 'umsdb'
    SqlUsername: 'umsuser'
    SqlPassword: 'Pass1@34'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: 'D:\a\1\s\umsdb\bin\Output\UMS.dacpac'
    IpDetectionMethod: 'AutoDetect'